export default {
  11: 'Superintendent',
  12: 'Deputy/Assistant Superintendent',
  13: 'Other District Administrator',
  21: 'Elementary Principal',
  22: 'Elementary Vice Principal',
  23: 'Secondary Principal',
  24: 'Secondary Vice Principal',
  25: 'Other School Administrator',
  31: 'Elementary Homeroom Teacher',
  32: 'Secondary Teacher',
  33: 'Other Teacher',
  34: 'Elementary Specialist Teacher',
  39: 'Orientation and Mobility Specialist',
  40: 'Other Support Personnel',
  41: 'Library Media Specialist',
  42: 'Counselor',
  43: 'Occupational Therapist',
  44: 'Social Worker',
  45: 'Speech-Language Pathologist or Audiologist',
  46: 'Psychologist',
  47: 'Nurse',
  48: 'Physical Therapist',
  49: 'Behavior Analyst',
  51: 'Extracurricular (Base Contract)',
  52: 'Substitute Teacher',
  61: 'Certificated on Leave or Buy Back',
  63: 'Contractor Teacher',
  64: 'Contractor Educational Staff Associate',
  90: 'Classified on Leave or Buy Back',
  91: 'Aide',
  92: 'Crafts or Trades',
  93: 'Laborer',
  94: 'Office or Clerical',
  95: 'Operator',
  96: 'Professional',
  97: 'Service Worker',
  98: 'Technical',
  99: 'Director or Supervisor',
};
